include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_dynamic_calls: error
    avoid_print: error
    empty_catches: error
    unawaited_futures: error

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_print: true
    empty_catches: true
    unawaited_futures: true
    prefer_final_locals: true
    prefer_single_quotes: true
